version: '3.4'
services:
  nginx-proxy:
    image: mila/reverseproxy 
    ports:
      - "80:80"
    depends_on: 
      - web
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  web:
    image: mila/wesele-app
    volumes:
      - .:/w
    ports:
      - 10535:10535
      - 3449:3449
    depends_on: 
      - mongo
    command: 'lein run'
    environment:
      TZ: 'Europe/Warsaw'
      CLOJURE_ENV: 'production'
  mongo:
    #image: mvertes/alpine-mongo
    image:  mila/mongo
    command: 'mongod --auth'
    ports:
      - 27017:27017
    volumes:
      - "/data/db:/data/db"
