version: '3.4'
services:
  web:
    image: mila/wesele-app
    volumes:
      - .:/w
    ports:
      - 10535:10535
      - 3449:3449
    depends_on: 
      - mongo
    command: 'lein run'
    environment:
      TZ: 'Europe/Warsaw'
      CLOJURE_ENV: 'development'
  mongo:
    image: mvertes/alpine-mongo
    ports:
      - 27017:27017
