version: '3.4'
services:
  nginx-proxy:
    image: mila/reverseproxy 
    ports:
      - "80:80"
    depends_on: 
      - web
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks: 
      - akwarium
  web:
    image: mila/wesele-app
    volumes:
      - .:/w
    ports:
      - 10535:10535
      - 3449:3449
      #- 7888:7888
      - 63254:63254
    depends_on: 
      - mongo
    command: 'lein run'
    environment:
      TZ: 'Europe/Warsaw'
      CLOJURE_ENV: 'production'
      FLICKR_SECRET: 'bc240567cff17332'
      IMGUR_SECRET: '4df4a4f44df033b89ddacddd906003d9fc66fce5'
    networks: 
      - akwarium
  mongo:
    #image: mvertes/alpine-mongo
    image:  mila/mongo
    command: 'mongod --auth'
    ports:
      - 27017:27017
    volumes:
      - "/data/db:/data/db"
    networks: 
      - akwarium
networks: 
  akwarium:
