version: '2'
services:
  web:
    image: 818228774882.dkr.ecr.eu-central-1.amazonaws.com/mila/wesele-app
    volumes:
      - /home/ec2-user/projects/wesele_app/wesele_app:/w
    ports:
      - 10535:10535
    links:
      - mongo
    command: 'lein run'
    environment:
      TZ: 'Europe/Warsaw'
      CLOJURE_ENV: 'development'
  mongo:
    image: mvertes/alpine-mongo
    ports:
      - 27017:27017
